Add jackson-databind dependency required by swagger-parser (#1406)
The swagger-parser library requires com.fasterxml.jackson.core:jackson-databind
at runtime (used by OpenAPIV3Parser static initializer). This was previously
provided transitively via opensearch-remote-metadata-sdk, which included it
through the opensearch-java client's Jackson 2 dependencies. After the SDK
migrated to Jackson 3, the transitive is no longer available, causing
NoClassDefFoundError in ApiSpecFetcherTests.

Signed-off-by: Daniel Widdis <widdis@gmail.com>
Signed-off-by: Dan Widdis <widdisd@amazon.com>